### ISSUE TITLE
Eversping SP814

### ISSUE THREAD

**Issue by IlyaKl** [ioBroker/ioBroker.zwave#10]
Dear Elias,
I have trouble connecting ever spring sp814 motion sensor to iobroker control with a aeon labs z-stick s2. Here is the log: 

zwave.0	2017-02-07 20:31:00.076	info	controller command feedback: state: "The command has completed successfully", error: "No error", helpmsg: "ControllerCommand - Completed"
zwave.0	2017-02-07 20:31:00.023	info	controller command feedback: state: "The command has failed", error: "No error", helpmsg: "ControllerCommand - Failed"
zwave.0	2017-02-07 20:30:59.362	info	controller command feedback: state: "The controller is communicating with the other device to carry out the command", error: "No error", helpmsg: "ControllerCommand - InProgress"

Regards,
Ilya

**Comment by carsten19** [comment]
@IlyaKl please verify with current version or close

**Comment by carsten19** [comment]
@Apollon77 can be closed
