### ISSUE TITLE
Zwave 1.7.3 Probleme nach Update von 1.6.3

### ISSUE THREAD

**Issue by Bibo13** [ioBroker/ioBroker.zwave#112]
Hi leute,
ich habe gerade einen Upgrade von Zwave 1.6.3 auf 1.7.3 gemacht.

Nach dem Neustart von Zwave habe ich nun folgenden Fehler im Log:

020-03-19 11:15:53.784 error Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
host.Elzershark 2020-03-19 11:15:53.784 error Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.Elzershark 2020-03-19 11:15:53.784 error Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.Elzershark 2020-03-19 11:15:53.783 error Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.Elzershark 2020-03-19 11:15:53.781 error Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.Elzershark 2020-03-19 11:15:53.781 error Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/openzwave-shared/lib/openzwave-shared.js:27:19)
host.Elzershark 2020-03-19 11:15:53.781 error Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.Elzershark 2020-03-19 11:15:53.780 error Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.Elzershark 2020-03-19 11:15:53.780 error Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:562:25)
host.Elzershark 2020-03-19 11:15:53.780 error Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
host.Elzershark 2020-03-19 11:15:53.779 error Caught by controller[0]: { Error: Cannot find module '/opt/iobroker/node_modules/openzwave-shared/lib/../build/Release/openzwave_shared.node'
zwave.0 2020-03-19 11:15:53.202 info (29552) Terminated (NO_ERROR): Without reason
zwave.0 2020-03-19 11:15:53.200 info (29552) terminating
zwave.0 2020-03-19 11:15:53.177 error (29552) Error: Cannot find module '/opt/iobroker/node_modules/openzwave-shared/lib/../build/Release/openzwave_shared.node' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:1
zwave.0 2020-03-19 11:15:53.175 error (29552) uncaught exception: Cannot find module '/opt/iobroker/node_modules/openzwave-shared/lib/../build/Release/openzwave_shared.node'
zwave.0 2020-03-19 11:15:52.906 info (29552) starting. Version 1.7.3 in /opt/iobroker/node_modules/iobroker.zwave, node: v10.19.0

Was kann ich tun damit er wieder startet?
viele Grüße und Danke

**Comment by Apollon77** [comment]
Plese install again and show log from install (or search log from last install in logfiles)

**Comment by Bibo13** [comment]
Welches Logfile meinen Sie? und wie soll ich installieren? Über IoBroker Adaper oder zu Fuß über NPM Befehl?

**Comment by Bibo13** [comment]
Nach längerem warten hier das Log. Es funktioniert immer noch nicht. Es ist das schon geschilderte Problem. Ich sollte vielleicht sagen das ich nicht von latest installiere sondern von stabil.
[zwave-log.txt](https://github.com/ioBroker/ioBroker.zwave/files/4354618/zwave-log.txt)

**Comment by Bibo13** [comment]
Können Sie mit dem Log etwas anfangen oder benötigen Sie noch andere Infos?

**Comment by Bibo13** [comment]
Problem gelöst.  AlCalzone hat darüber schon mal geschrieben.


cd /opt/iobroker/node_modules/openzwave-shared
sudo -H npm i --production --unsafe-perm 

Danach Reboot razberry
Alles läuft wieder.
