### ISSUE TITLE
JavaScript selector fails

### ISSUE THREAD

**Issue by kvaster** [ioBroker/ioBroker.zwave#16]
In my setup I am using selector: $('state[role=value.battery]) but it fails with error - can't find 'common' in undefined object.
After investigation I found that there are such id's in selector: zwave.0.NODE9.awake
And it appears that there is no object (getObject returns null) for such ids (*.awake)

**Comment by Apollon77** [comment]
Please provide the full error including file lines and such  ...

**Comment by kvaster** [comment]
I am really sorry, but it seems that something was wrong at my install. Can't reproduce after iobroker restart - all is working fine now.
