### ISSUE TITLE
Should we move 0.8 to stable?

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.zwave#24]
It has been out for a while now. 
Also, the changes from #21 to #23 have been on GitHub for a few weeks, we should probably move to 0.9.

**Comment by Apollon77** [comment]
I do not see any reasy not to do it :-)

**Comment by AlCalzone** [comment]
I just released v0.9.0 on GitHub: https://github.com/ioBroker/ioBroker.zwave/commit/5b164bd991ef3b51e2a525fd3f2e07daf595ddf7
please publish on NPM @GermanBluefox

**Comment by DutchmanNL** [comment]
on NPM latest versions in latest = 0.7.0, just installed 0.9 from git which works well

**Comment by AlCalzone** [comment]
Seems this is resolved now
