### ISSUE TITLE
Z-Wave Secure Boiler Receiver HRT - doesnt update relay status

### ISSUE THREAD

**Issue by vladitep** [ioBroker/ioBroker.zwave#26]
Device marked as supported, added to openzwave properly, shown as it should, i can control relay position, but cant see relay status if it change by thermostat.
With vera lite, relay status shown properly, so receiver send it to controller, but when i try to use it with openzwave - i can not see state, openzwave ignore state change

**Comment by AlCalzone** [comment]
Might I redirect you to the openzwave repository? https://github.com/OpenZWave/open-zwave/issues
This adapter is just using the openzwave library.

**Comment by AlCalzone** [comment]
closing, since we can't do anything about it
