### ISSUE TITLE
Open/Close states for blinds do something weird.

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.zwave#29]
I'll check it out.

**Comment by matthiasgasser** [comment]
Hi!

Any update on this? I've got the FGRM222 Roller Shutter Controller 2 and I also experience weird behaviour of the states as well as if I manually control the blinds (with the regular wall switch) the blinds are closing and opening again. Sometimes after a they were all closed, sometimes after a few seconds.

Any idea?

thx!

**Comment by arteck** [comment]
its simple...
I do not know why but these 2 come only after the restart

**Comment by arteck** [comment]
its simple...
I do not know why but these 2 come only after the restart

**Comment by carsten19** [comment]
@AlCalzone what is this all about? I do have 2 of those roller shutters and they work flawless

**Comment by AlCalzone** [comment]
I'm not sure anymore. This was because of a report in the forum. For me they work flawlessly too.

**Comment by carsten19** [comment]
Then just close it I guess
