### ISSUE TITLE
Can i use Aeotec AEOEZW090-C ?

### ISSUE THREAD

**Issue by eXplOiD1** [ioBroker/ioBroker.zwave#32]
can i use this one ?

[https://www.amazon.de/Aeotec-AEOEZW090-C-Stick-eingebauter-Batterie/dp/B00YETCNOE/ref=sr_1_2?ie=UTF8&qid=1516127243&sr=8-2&keywords=zwave+usb+stick](url)

**Comment by Apollon77** [comment]
Best ask in Forum or try it ;-)
