### ISSUE TITLE
Bump to 1.0.0 and publish on stable?

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.zwave#33]
The latest changes seem stable [(see forum)](http://forum.iobroker.net/viewtopic.php?f=36&t=10607) and I think this is mature enough for a 1.x version.

So I propose we bump this to 1.0.0 and publish it (I can't do the latter one though).

**Comment by Apollon77** [comment]
Should we add Admin3 support first and release this then as 1.0.0 ?!

**Comment by AlCalzone** [comment]
You have a point there, i agree.

**Comment by GermanBluefox** [comment]
The configuration is rather complex, so I am not sure if someone can do it in the near future. I have nothing against to 1.0 without admin3 interface.

**Comment by Apollon77** [comment]
If it is that complicated, go

**Comment by AlCalzone** [comment]
I bumped the version in 66d6db9, please publish to NPM @GermanBluefox.

**Comment by Apollon77** [comment]
Publish done
