### ISSUE TITLE
No feedback from the config UI in Admin 3

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.zwave#34]
Buttons correctly set the controller in inclusion mode, etc. but no feedback reaches the admin UI and buttons don't get updated. Because of that, inclusion can only be stopped by restarting the adapter - which can take a long time on large networks.

**Comment by GermanBluefox** [comment]
It must be: 
https://github.com/ioBroker/ioBroker.zwave/blob/master/admin/index.html#L498

`socket.emit('subscribe',  'zwave.' + instance + '.*');`

**Comment by carsten19** [comment]
@AlCalzone should be closed?

**Comment by carsten19** [comment]
@Apollon77 please close, thank you
