### ISSUE TITLE
Netzwerk Informationen Einblenden

### ISSUE THREAD

**Issue by JackWolfskin42** [ioBroker/ioBroker.zwave#36]
Z.B. so wie das bei Domoticz (auch open zwave basiert) darstellt:
[ZWave Netzwerk Anzeige](http://www.domoticz.com/wiki/Zwave#Network_and_group_info)

**Comment by AlCalzone** [comment]
Coole Sache. Ich bin aktuell ziemlich unzufrieden was die Entwicklung(sgeschwindigkeit) von OpenZWave angeht (die Library, die unser Adapter verwendet). Daher schreibe ich an einem eigenen Treiber, mit dem ich langfristig OZW ersetzen will: https://github.com/AlCalzone/node-zwave-js - der braucht allerdings noch einige Zeit.

Wenn das fertig ist, könnte ich mir sowas anschauen.

**Comment by JackWolfskin42** [comment]
Cool , aber klingt auch recht "ambitioniert"   ;-)
Wenn ich mir anschaue wie lange in openhab bereits die eigene Entwicklung eines z-wave Adapters braucht, und angesichts der fast nicht frei verfügbaren Doku, bin ich da mal erst ein bischen skeptisch.
Aber ich bin da noch nicht so tief in z-wave drin, aber bisher erschien mir open zwave noch eine der "stabilsten" Libraries .... also wenn ich das so mit anderen vergleiche. Klar, es steht bei z-wave aber alles mit der Database... nur ob man die selbst verwalten will?

**Comment by AlCalzone** [comment]
> fast nicht frei verfügbaren Doku

Die CommandClasses sind sehr gut dokumentiert inzwischen, lediglich die Schnittstelle zum Stick ist nicht frei erhältlich, aber da hab ich mit OZW und OpenHab gute Vorlagen.
Bei OZW nervt mich die langsame Entwicklung. Der PR zur Verbesserung der CentralScene CommandClass liegt seit 14 Monaten (!) brach, obwohl anscheinend fast funktionsfähig. Mein PR für MultilevelSwitch V4 seit inzwischen 7 Monaten...

Glaube auch nicht, dass die Datenbank das riesen Problem wird. Die Geräte sind eigentlich selbstbeschreibend, OZW hat halt ne recht gute Beschreibung der einzelnen Parameter

**Comment by carsten19** [comment]
Wäre es dann nicht sinnvoller, einen Adapter für die Integration von Domoticz zu haben und die zwave Steuerung nicht selber zu treiben?

**Comment by AlCalzone** [comment]
Bei OZW geht es neuerdings wieder voran.
Außerdem nähert sich meine [ZWave-Library](https://github.com/AlCalzone/node-zwave-js) der Nutzbarkeit - mit der will ich einen eigenen ZWave-Adapter bauen. Da können auch solche Informationen wie das Netzwerk extrahiert werden.

**Comment by carsten19** [comment]
BTW: eine map Ansicht hat auch der zigbee Adapter.
In welche Richtung geht dann die Entwicklung? Die neue ZWave-Library oder Verbesserungen in dem aktuellen Adapter?

**Comment by AlCalzone** [comment]
Ich werde voraussichtlich keine großen Mühen in diesen Adapter stecken, da die Version, die auf der Library aufbaut, anders ticken muss. Solche Dinge wie du in letzter Zeit gemeldet hast, werde ich aber berücksichtigen.

**Comment by carsten19** [comment]
Hab einen PR dazu erstellt

**Comment by carsten19** [comment]
@JackWolfskin42 ist in der github Version verfügbar

**Comment by carsten19** [comment]
@Apollon77 can be closed
