### ISSUE TITLE
MCOHome CO2 monitor returns zero values

### ISSUE THREAD

**Issue by AlexVVVx** [ioBroker/ioBroker.zwave#40]
The device was successfully added but it does not return CO2, temperature and humidity values. I see 0 all the time.  The instructions suggest to associate a gateway with Group 2. The Group 2 is in the list on  the association tab but disabled (cannot be edited).  
I have no any other idea how to get it working. 

Thank you.

**Comment by OleksiyAntonov** [comment]
It seems like MCOHome sensor doesn´t send updates.
In my case I added sensor to the network and update parameters according with MCOHome manual to send update when humidity changed in 1%, CO2 in 25 ppm and temperature every 0.5 grad.
Everything works fine (just need to wait some time for the next value changes).
I try to find Z-Wave command to initiate manual reporting of current values to force data update but now I don´t have success.

**Comment by carsten19** [comment]
@AlexVVVx can you confirm if that is still an issue?

**Comment by AlexVVVx** [comment]
I confirm that using version 1.6 I can see all the data but they are not being updated. I see new values only after the adapter restart.
Thank you. It is getting better.

**Comment by carsten19** [comment]
In this case it would be great if you could start the adapter with debug mode. And then post the log when the values **should** be updated.

**Comment by carsten19** [comment]
@AlexVVVx I don't think we can do more from an adapter perspective as we just receive the values from openzwave. Please close.

**Comment by AlexVVVx** [comment]
@cburghardt  Ok. I will close this issue. 
Thank you for your efforts.
