### ISSUE TITLE
USB Device Name

### ISSUE THREAD

**Issue by Marsx79** [ioBroker/ioBroker.zwave#42]
Is it possible  to use the "com port ID" (/dev/serial/by-id/) at the "USB Device Name" like the Zigbee Adapter?

**Comment by snador1977** [comment]
I would like to support this. I have 2 sticks (Zigbee + Z-Wave) on the computer and they change the port during the reboot. An integration (like alternative) would fix the problem. Thank you!

**Comment by fabiankrauss** [comment]
Ja ist das vllt möglich? das wäre sehr praktisch

**Comment by AlCalzone** [comment]
Can you guys try to stop the adapter (so the dropdown does not show), open the admin UI and enter that path manually?

**Comment by fabiankrauss** [comment]
I tryed it yesterday. In V 1.3.1 there is still only a dropdownmenu when I stop it. I can't write an adress in it.
I downdated to V1.2.0  there shows up a inputfield when I stop the adapter. But it doesn't save the value.

**Comment by snador1977** [comment]
Does not work with me, it is only a dropdown available

**Comment by carsten19** [comment]
I highly recommend to use symlinks for the devices as described for example here:
https://www.domoticz.com/wiki/Assign_fixed_device_name_to_USB_port

So I use those symlinks for zwave as well as for zigbee.

**Comment by carsten19** [comment]
@Marsx79 , @snador1977: has been implemented

**Comment by carsten19** [comment]
@Apollon77 can be closed
