### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by bergjet** [ioBroker/ioBroker.zwave#43]
`$ ./iobroker url "https://github.com/ioBroker/ioBroker.zwave.git"
install https://github.com/ioBroker/ioBroker.zwave/tarball/master
npm install https://github.com/ioBroker/ioBroker.zwave/tarball/master --production --save --prefix "/opt/iobroker" (System call)
find: ‘/tmp/systemd-private-274bcfdb90a64e5bb90c89a10a313fb3-redis-server.service-Gc20Qv’: Keine Berechtigungfind: ‘/tmp/systemd-private-274bcfdb90a64e5bb90c89a10a313fb3-fwupd.service-pmJVmQ’: Keine Berechtigung
find: ‘/tmp/systemd-private-274bcfdb90a64e5bb90c89a10a313fb3-bolt.service-azBFEs’: Keine Berechtigung
find: ‘/tmp/systemd-private-274bcfdb90a64e5bb90c89a10a313fb3-colord.service-o5llKv’: Keine Berechtigung
find: ‘/tmp/systemd-private-274bcfdb90a64e5bb90c89a10a313fb3-rtkit-daemon.service-dQLIfs’: Keine Berechtigung
find: ‘/tmp/systemd-private-274bcfdb90a64e5bb90c89a10a313fb3-systemd-resolved.service-Cb3UNP’: Keine Berechtigung
find: ‘/tmp/systemd-private-274bcfdb90a64e5bb90c89a10a313fb3-systemd-timesyncd.service-WBylGI’: Keine Berechtigung
find: ‘/tmp/ssh-ylh5EtJtkrjt’: Keine Berechtigung
`

**Comment by AlCalzone** [comment]
Aktuell muss über die Konsole installiert werden... Wir arbeiten dran.
```
cd /opt/iobroker 
npm i iobroker.zwave --unsafe-perm
```

**Comment by AlCalzone** [comment]
Und dann im admin eine Instanz hinzufügen

**Comment by bergjet** [comment]
Keine Änderung.
Schon bei der Installation kommt:

`martin@beelink:/opt/iobroker$ npm i iobroker.zwave --unsafe-perm

> openzwave-shared@1.4.6 preinstall /opt/iobroker/node_modules/openzwave-shared
> node lib/install-ozw.js


> iobroker.zwave@1.3.1 preinstall /opt/iobroker/node_modules/iobroker.zwave
> node lib/preinstall.js

---> find /tmp -name 'CentralScene.h'
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-systemd-resolved.service-nTRoZQ’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-redis-server.service-J7sMTw’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-rtkit-daemon.service-nTdDmt’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-colord.service-VrWPwB’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-systemd-timesyncd.service-BggfPJ’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-fwupd.service-kOzdcS’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-bolt.service-ew5GXt’: Keine Berechtigung
---> Error: Command failed: find /tmp -name 'CentralScene.h'
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-systemd-resolved.service-nTRoZQ’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-redis-server.service-J7sMTw’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-rtkit-daemon.service-nTdDmt’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-colord.service-VrWPwB’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-systemd-timesyncd.service-BggfPJ’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-fwupd.service-kOzdcS’: Keine Berechtigung
find: ‘/tmp/systemd-private-982f6ff0f90b400fbf35cec10850d79d-bolt.service-ew5GXt’: Keine Berechtigung

---> find /usr/include/ -name 'CentralScene.h'
---> find /usr/local/include/ -name 'CentralScene.h'
CentralScene.h found in /usr/local/include/openzwave/command_classes/CentralScene.h

---> find /usr/local/include/ -name 'CentralScene.h'|grep 'createSupportedKeyAttributesValues'
---> Error: Command failed: find /usr/local/include/ -name 'CentralScene.h'|grep 'createSupportedKeyAttributesValues'
---> sudo apt-get install libudev-dev -y
[sudo] Passwort für martin: 
---> curl -L -O https://github.com/OpenZWave/open-zwave/archive/master.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0    195      0 --:--:-- --:--:-- --:--:--   194
100 1878k    0 1878k    0     0   851k      0 --:--:--  0:00:02 --:--:-- 3415k
---> rm -rf open-zwave-master
---> unzip master.zip && rm master.zip
---> cd open-zwave-master && curl -O -L https://github.com/OpenZWave/open-zwave/pull/1125.patch && patch -p1 < 1125.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    318      0 --:--:-- --:--:-- --:--:--   318
100 16081    0 16081    0     0  11798      0 --:--:--  0:00:01 --:--:--  149k
---> cd open-zwave-master && make && sudo make install
Makefile:224: Documentation not being built

> openzwave-shared@1.4.6 install /opt/iobroker/node_modules/openzwave-shared
> node-gyp rebuild

make: Verzeichnis „/opt/iobroker/node_modules/openzwave-shared/build“ wird betreten
  CXX(target) Release/obj.target/openzwave_shared/src/callbacks.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-config.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-driver.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-groups.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-management.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-network.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-nodes.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-polling.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-scenes.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-values.o
  CXX(target) Release/obj.target/openzwave_shared/src/utils.o
  SOLINK_MODULE(target) Release/obj.target/openzwave_shared.node
  COPY Release/openzwave_shared.node
make: Verzeichnis „/opt/iobroker/node_modules/openzwave-shared/build“ wird verlassen
+ iobroker.zwave@1.3.1
added 2 packages from 25 contributors and audited 6192 packages in 219.64s
found 75 vulnerabilities (55 low, 1 moderate, 19 high)
  run `npm audit fix` to fix them, or `npm audit` for details
martin@beelink:/opt/iobroker$ 
`

**Comment by AlCalzone** [comment]
Sieht doch gut aus! Vielleicht sollten die "Fehler"-Meldungen unterdrückt werden, aber der Adapter ist installiert:
```
iobroker.zwave@1.3.1
added 2 packages from 25 contributors and audited 6192 packages in 219.64s
```

**Comment by AlCalzone** [comment]
Übrigens: Die Installation von GitHub (wie im ersten Post) sollte nur in Ausnahmefällen geschehen!
Bitte unbedingt lesen => http://www.iobroker.net/docu/?page_id=8511&lang=de#zusaetzliche_wichtige_Informationen

**Comment by bergjet** [comment]
Hilft aber nichts. Kein Port zum auswählen.
<img width="438" alt="screenshot 2019-01-14 16 48 10" src="https://user-images.githubusercontent.com/4241968/51123414-55413b00-181c-11e9-8a3c-215bfaeeccd5.png">

**Comment by AlCalzone** [comment]
Da brauche ich etwas mehr Info...
Welche Hardware? Wenn RasPi 3 + GPIO-Platine, dann [hier lesen](https://github.com/ioBroker/ioBroker.zwave#raspberry-pi3-only-activate-gpio-uart).
Stehen Fehler im Log? Läuft der Adapter?

**Comment by bergjet** [comment]
Es ist ein Beelink S2
Es sind nun einmal im Fenster USB Device einmal eine Anzeige ttyACM1 (ein anderes mal ttyACM0) gekommen, ich konnte auch Geräte anlernen. Nach einem Neustart ist das USB Device Name Fenster aber wieder leer.

failed to start driver
starting. Version 1.3.1 in /opt/iobroker/node_modules/iobroker.zwave, node: v8.15.0
instance system.adapter.zwave.0 started with pid 2785
nstance system.adapter.zwave.0 terminated with code null ()
nstance system.adapter.zwave.0 terminated due to SIGSEGV
stopInstance system.adapter.zwave.0 killing pid 2686
stopInstance system.adapter.zwave.0

**Comment by AlCalzone** [comment]
> Nach einem Neustart ist das USB Device Name Fenster aber wieder leer.

Das liegt daran, dass der Adapter wegen Fehlern permanent neu startet.

> failed to start driver

Sonst nix? https://github.com/ioBroker/ioBroker.zwave#known-issues mal durchgearbeitet?

**Comment by bergjet** [comment]
Ja, ausser dem vom Raspberry.

**Comment by Iofreund** [comment]
Diese Einstellung hat bei mir geholfen: "Driver Attempts" von 3 auf 6 erhöhen.
![bildschirmfoto 2019-02-01 um 13 26 29](https://user-images.githubusercontent.com/47245413/52123035-2cdf7c00-2625-11e9-905a-92e82de55bd8.png)
Hardware: Beelink S2, Zwave stick von wd (ZME_UZB1)
Software: Debian 9, node v8.15.0, npm 6.4.1

**Comment by csaeum** [comment]
Also ich habe auch die Meldungen wie oben mit Keine Berechtigung usw.
Ich habe mir vor 2 Wochen einen Raspi mit der Razberry Platine gekauft. 
Habe damals den Adapter installiert bekommen aber die Instanz war immer rot oder gelb.

Nach abstecher zu ZWAVE.ME und OpenHab will ich nun iobroker nochmal testen weil dort einige Sachen einfacher gehen oder es auch für Shelly usw Adapter gibt.

Ich bin langsam verzweifelt weil selbst mit einen fertigen Image der Adapter sich nicht installiert, gestern auch mit Buster und Stretch und den 3 Zeiler zum installieren, wird der Adapter nicht installiert.

Ich bin langsam absolut Ratlos, welche Daten würdet ihr benötigen um diese Fehler und das nicht möglich installieren zu analysieren?

Gerne auch per E-Mail oder per Forum, aber dort war es bis jetzt eine Alleinunterhaltung!

**Comment by AlCalzone** [comment]
@csaeum Mindestens mal die Ausgabe deiner Installationsversuche.

**Comment by csaeum** [comment]
Danke @AlCalzone 

also heute morgen bekam ich in Facebook von einen den Tip das Fixer auszuführen.
Zu der Installation: Es ist ein Stretch lite mit iobroker 3 Zeiler aus der Doku.
Der Fixer ist schon ausgeführt aber davor und danach war diese Meldung, hat sich also nichts verändert:

> pi@raspberrypi:/opt/iobroker $ sudo -H npm i iobroker.zwave --unsafe-perm --production
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b ozw-1.4 git://github.com/AlCalzone/node-openzwave-shared.git /root/.npm/_cacache/tmp/git-clone-12956e66
npm ERR! fatal: Konnte führende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-12956e66' nicht erstellen.: Keine Berechtigung
npm ERR! 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-01T06_35_55_830Z-debug.log
pi@raspberrypi:/opt/iobroker $

Hier dann nochmal die Meldung vom installieren:
>pi@raspberrypi:/opt/iobroker $ sudo -H iobroker add zwave
NPM version: 6.9.0
npm install iobroker.zwave@1.3.1 --unsafe-perm --production --save --prefix "/opt/iobroker" (System call)
find: ‘/tmp/systemd-private-bbadc3d2d22546fb9cab06400535e0f9-systemd-timesyncd.service-DxaF1u’: Keine Berechtigung
find: ‘/etc/polkit-1/localauthority’: Keine Berechtigung
find: ‘/etc/ssl/private’: Keine Berechtigung
find: ‘/tmp/systemd-private-bbadc3d2d22546fb9cab06400535e0f9-systemd-timesyncd.service-DxaF1u’: Keine Berechtigung
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0    291      0 --:--:-- --:--:-- --:--:--   290
100 12.4M    0 12.4M    0     0  1297k      0 --:--:--  0:00:09 --:--:-- 1511k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    346      0 --:--:-- --:--:-- --:--:--   346
100 16081    0 16081    0     0  16099      0 --:--:-- --:--:-- --:--:-- 16099
/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:16
    if (!suppressException) throw e;
                            ^

>Error: Command failed: cd open-zwave-master && curl -O -L https://github.com/OpenZWave/open-zwave/pull/1125.patch && patch -p1 < 1125.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    346      0 --:--:-- --:--:-- --:--:--   346
100 16081    0 16081    0     0  16099      0 --:--:-- --:--:-- --:--:-- 16099

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at doScript (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:13:15)
    at installOpenZwaveFromSource (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:147:3)
    at installOpenZwave (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:139:3)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:27:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.3 (node_modules/osx-temperature-sensor):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.zwave@1.3.1 preinstall: `node lib/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iobroker.zwave@1.3.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2019-07-01T09_08_13_310Z-debug.log
host.raspberrypi install adapter zwave
NPM version: 6.9.0
npm install iobroker.zwave@1.3.1 --unsafe-perm --production --save --prefix "/opt/iobroker" (System call)
find: ‘/tmp/systemd-private-bbadc3d2d22546fb9cab06400535e0f9-systemd-timesyncd.service-DxaF1u’: Keine Berechtigung
find: ‘/etc/polkit-1/localauthority’: Keine Berechtigung
find: ‘/etc/ssl/private’: Keine Berechtigung
find: ‘/tmp/systemd-private-bbadc3d2d22546fb9cab06400535e0f9-systemd-timesyncd.service-DxaF1u’: Keine Berechtigung
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0    298      0 --:--:-- --:--:-- --:--:--   299
100 12.4M    0 12.4M    0     0  1331k      0 --:--:--  0:00:09 --:--:-- 1572k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    310      0 --:--:-- --:--:-- --:--:--   311
100 16081    0 16081    0     0  17381      0 --:--:-- --:--:-- --:--:-- 41022
/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:16
    if (!suppressException) throw e;
                            ^

Error: Command failed: cd open-zwave-master && curl -O -L https://github.com/OpenZWave/open-zwave/pull/1125.patch && patch -p1 < 1125.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    310      0 --:--:-- --:--:-- --:--:--   311
100 16081    0 16081    0     0  17381      0 --:--:-- --:--:-- --:--:-- 41022

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at doScript (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:13:15)
    at installOpenZwaveFromSource (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:147:3)
    at installOpenZwave (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:139:3)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:27:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.3 (node_modules/osx-temperature-sensor):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.zwave@1.3.1 preinstall: `node lib/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iobroker.zwave@1.3.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2019-07-01T09_09_02_817Z-debug.log
host.raspberrypi install adapter zwave
NPM version: 6.9.0
npm install iobroker.zwave@1.3.1 --unsafe-perm --production --save --prefix "/opt/iobroker" (System call)
find: ‘/tmp/systemd-private-bbadc3d2d22546fb9cab06400535e0f9-systemd-timesyncd.service-DxaF1u’: Keine Berechtigung
find: ‘/etc/polkit-1/localauthority’: Keine Berechtigung
find: ‘/etc/ssl/private’: Keine Berechtigung
find: ‘/tmp/systemd-private-bbadc3d2d22546fb9cab06400535e0f9-systemd-timesyncd.service-DxaF1u’: Keine Berechtigung
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0     59      0 --:--:--  0:00:02 --:--:--    59
100 12.4M  100 12.4M    0     0   346k      0  0:00:36  0:00:36 --:--:-- 1217k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    236      0 --:--:-- --:--:-- --:--:--   237
100 16081    0 16081    0     0  13660      0 --:--:--  0:00:01 --:--:-- 34657
/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:16
    if (!suppressException) throw e;
                            ^

Error: Command failed: cd open-zwave-master && curl -O -L https://github.com/OpenZWave/open-zwave/pull/1125.patch && patch -p1 < 1125.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    236      0 --:--:-- --:--:-- --:--:--   237
100 16081    0 16081    0     0  13660      0 --:--:--  0:00:01 --:--:-- 34657

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at doScript (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:13:15)
    at installOpenZwaveFromSource (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:147:3)
    at installOpenZwave (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:139:3)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:27:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.3 (node_modules/osx-temperature-sensor):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.zwave@1.3.1 preinstall: `node lib/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iobroker.zwave@1.3.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2019-07-01T09_10_21_952Z-debug.log
host.raspberrypi install adapter zwave
host.raspberrypi Cannot install zwave
pi@raspberrypi:/opt/iobroker $

Das wären diese Logs usw

**Comment by AlCalzone** [comment]
Ich sehe der versucht 1.3.1 zu installieren. Das geht nicht mehr, da die Installationsroutine durch eine Änderung im OpenZWave-Repo kaputt gemacht wurde. Installiere mal manuell die 1.4.1 (war noch nicht im stable-repo):
```
cd /opt/iobroker
npm i iobroker.zwave
```
Das hast du im ersten Schritt zwar probiert, aber irgendwie mit root und so...

**Comment by csaeum** [comment]
Aber so mach ich es schon immer oder über den Admin und er zeigt mir auch im Admin immer die 1.3.1 an und nicht die 1.4.x

Ich werde es probieren aber er wird wieder die 1.3.x nehmen

**Comment by csaeum** [comment]
Ok danke für die Hilfe
Er hat nun die 1.4.1 installiert:
Er zeigt mir beim Adapter nun an: 

> Verfügbare Version: 1.3.1 - Installierte Version: 1.4.1

Beim installieren der Instanz kommt:

> Fertig mit Fehler: fs.js:114 throw err; ^ Error: EACCES: permission denied, open '/opt/iobroker/node_modules/iobroker.zwave/iob_npm.done' at Object.openSync (fs.js:443:3) at Object.writeFileSync (fs.js:1194:35) at ChildProcess.child.on (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:2938:20) at ChildProcess.emit (events.js:198:13) at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) 

sowie im Admin-Fenster:

> $ ./iobroker add zwave  --host raspberrypi
host.raspberrypi install adapter zwave
npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.zwave"
find: ‘/tmp/systemd-private-bbadc3d2d22546fb9cab06400535e0f9-systemd-timesyncd.service-DxaF1u’: Keine Berechtigung
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   122    0   122    0     0    284      0 --:--:-- --:--:-- --:--:--   285

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file 1.4.zip: Keine Berechtigung

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (23) Failed writing body (0 != 54)

/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:16    if (!suppressException) throw e;
                            ^

Error: Command failed: curl -L -O https://github.com/OpenZWave/open-zwave/archive/1.4.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   122    0   122    0     0    284      0 --:--:-- --:--:-- --:--:--   285

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file 1.4.zip: Keine Berechtigung

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (23) Failed writing body (0 != 54)

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at doScript (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:13:15)
    at installOpenZwaveFromSource (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:145:3)
    at installOpenZwave (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:139:3)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zwave/lib/preinstall.js:27:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

npm
 
ERR! code ELIFECYCLEnpm ERR! errno 1

npm
 ERR! iobroker.zwave@1.4.1 preinstall: `node lib/preinstall.js`npm ERR! Exit status 1
npm ERR! 
npm
 ERR! Failed at the iobroker.zwave@1.4.1 preinstall script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm
 WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-07-01T12_19_10_463Z-debug.log

ERROR: fs.js:114    throw err;
    ^

Error: EACCES: permission denied, open '/opt/iobroker/node_modules/iobroker.zwave/iob_npm.done'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at ChildProcess.child.on (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:2938:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

ERROR: process exited with code 1

**Comment by AlCalzone** [comment]
Ich schätze deine vorherigen Versuche haben die Berechtigungen in `/opt/iobroker/node_modules/iobroker.zwave` zerstört. Lass mal den Fixer laufen.

**Comment by csaeum** [comment]
Danke mit den Fixer ist die Instanz endlich am laufen.

Nun muss ich nur noch den Adapter richtig einstellen das Z-Wave und Bluetooth funktionieren.

Danke @AlCalzone  für deine Hilfe.

**Comment by bloodhound83** [comment]
Hello @AlCalzone,

bekomme aktuell den Adapter nicht mehr installiert.
Habe ein frisches Image vom IObroker genutzt, um Altlasten auszuschließen.
Sowohl über die Oberfläche und auch übers Terminal kein Erfolg.
Fixer hatte ich auch schon laufen lassen..


$ ./iobroker add zwave  --host Heimdall
NPM version: 6.4.1
npm install iobroker.zwave --unsafe-perm --production --save --prefix "/opt/iobroker" (System call)
find: ‘/tmp/systemd-private-36c255f6660f424b9c36e877a4d9994a-systemd-timesyncd.service-3TyzLX’: Keine Berechtigung
find: ‘/etc/polkit-1/localauthority’: Keine Berechtigungfind: ‘/etc/ssl/private’: Keine Berechtigung

find: ‘/tmp/systemd-private-36c255f6660f424b9c36e877a4d9994a-systemd-timesyncd.service-3TyzLX’: Keine Berechtigung
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   122    0   122    0     0    266      0 --:--:-- --:--:-- --:--:--   266

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 14423    0 14423    0     0   7147      0 --:--:--  0:00:02 --:--:-- 15311
100  878k    0  878k    0     0   285k      0 --:--:--  0:00:03 --:--:--  439k
100 1917k    0 1917k    0     0   581k      0 --:--:--  0:00:03 --:--:--  863k

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   147    0   147    0     0    313      0 --:--:-- --:--:-- --:--:--   314

100 16081    0 16081    0     0  14854      0 --:--:--  0:00:01 --:--:-- 14854

**Comment by carsten19** [comment]
@bergjet bitte schließen
