### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [ioBroker/ioBroker.zwave#45]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/ioBroker/ioBroker.zwave

- [ ] [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.zwave"
- [ ] [E301] Tests on Travis-ci.org are broken. Please fix.

Thanks,
your automatic adapter checker.

**Comment by AlCalzone** [comment]
E016, E116 fixed by 16dea91
W113, E117 fixed by b0c7e18
E605 fixed by c1af2e5

**Comment by AlCalzone** [comment]
E201 is a false positive

**Comment by carsten19** [comment]
@Apollon77 can be closed, all done in 1.7.0
