### ISSUE TITLE
Cannot delete devices which are not recognized properly

### ISSUE THREAD

**Issue by easybeat** [ioBroker/ioBroker.zwave#46]
Hi
I have several problems with Nodon Wallswitches. The include process doesn't work properly but this is maybe more a Nodon problem. But now I have about 5 devices in my device list and when I choose delete device from the option list the OK message appears but nothing happens.
![Zwave cannot delete device](https://user-images.githubusercontent.com/37217887/55647512-21076600-57de-11e9-809d-2c9e95dd2cba.JPG)

I'm using a Aeotec ZW090 Gen5 Stick and it works perfect with all other devices and brands.
![Zwave Stick](https://user-images.githubusercontent.com/37217887/55647556-45634280-57de-11e9-8ace-7a449b85a47f.JPG)

Is there some advice you can give me how to remove them devices?

Thanks and kind regards
Beat

**Comment by AlCalzone** [comment]
I'm not sure if this is still relevant. You could try and delete the corresponding objects from ioBroker.
So just delete the entire tree `zwave.0.NODE035` and `zwave.0.NODE40`, then restart the adapter.

**Comment by easybeat** [comment]
I tried this but it doesn't work. The device just doesn't go in the zwave adapter device list.

Thanks
Beat

**Comment by Bluelightcrew** [comment]
Ich have the same problem

**Comment by carsten19** [comment]
Some proposals:
- don't put the stick into pairing mode but simply make the device try to pair (press button or whatever). For me that turned the unknown device into a known device
- reset the device and then delete it from the device list
- try the unpair functionality of the stick (long press the button on it) and the unpair the device

**Comment by carsten19** [comment]
@easybeat please verify if those proposals work. If not, please post a log in debug mode when you try to delete the device.

**Comment by easybeat** [comment]
@cburghardt Ok will do this in the next couple of days...

**Comment by carsten19** [comment]
@easybeat any updates?

**Comment by easybeat** [comment]
Hi

yes sorry...none of your proposals did work for me as I cannot figure out which unknown device is which physical device. If I try to add one which is not properly on it just adds another new one.

I will try to edit the devicelist directly with the aeotec software and delete the unknown devices from the stick. I've got a second stick now so I can backup before I start...

And then hopefully I will be able to delete the devices also in ioBroker.

I will keep you updated.

Thanks

Beat

**Comment by carsten19** [comment]
If you are using the latest version of z-wave you can also try refresh of the device. That deletes it and adds it - when it finds it.

**Comment by carsten19** [comment]
Version 1.6.3 also has the option to remove failed devices

**Comment by carsten19** [comment]
@Apollon77 can be closed, no further possibility from an adapter perspective
