### ISSUE TITLE
Confirmation for destructive action 

### ISSUE THREAD

**Issue by carsten19** [ioBroker/ioBroker.zwave#52]
I just clicked by accident on the hard reset button and was shocked that all my zwave devices where wiped out. While the function works as expected I would recommend a confirmation dialog.

**Comment by carsten19** [comment]
@AlCalzone I will provide a PR for this. I am missing the i18n sources in the repository?

**Comment by AlCalzone** [comment]
I think there is a gulp command to generate those... but don't ask me which. I'm using those too seldom.

**Comment by carsten19** [comment]
@Apollon77 do you know how that works if I need to add new strings to the admin page? The generated output is words.js in the admin directory but I have no idea how to generate that.

**Comment by DutchmanNL** [comment]
@cburghardt hope this helps ?

https://forum.iobroker.net/topic/19047/gulp-ist-kein-hexenwerk-auto-translation

**Comment by carsten19** [comment]
@DutchmanNL awesome, that was the solution
@AlCalzone PR created

**Comment by carsten19** [comment]
Implemented
