### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by carsten19** [ioBroker/ioBroker.zwave#53]
I just upgraded to version 1.4.2. As that version changes the regex to also exclude white space I now have lots of duplicate states.
![Bildschirmfoto 2019-07-03 um 11 01 51](https://user-images.githubusercontent.com/839480/60578735-04011580-9d82-11e9-8750-b8228b54a9fb.png)

Do I have to delete the old ones with whitespace?

**Comment by AlCalzone** [comment]
Yes, the ones with spaces are not supposed to be there. They used to be replaced with _, but a JS-Controller update broke that. You can delete all states with spaces (or the entire object tree and let the adapter recreate it on restart).

**Comment by carsten19** [comment]
Clarified
