### ISSUE TITLE
v1.5.0 Fibaro Wall Plug - no Switch Binary

### ISSUE THREAD

**Issue by jupzup** [ioBroker/ioBroker.zwave#59]
With the last Update the Command Class Switch Binary will not create so the Wall Plug can not be switched on / off.

**Comment by AlCalzone** [comment]
Try refreshing the device information. We have no control over what data OpenZWave sends us.

**Comment by Pmant** [comment]
Same with Fibaro Switch 2. Might be this:
https://github.com/OpenZWave/open-zwave/issues/1878

**Comment by Pmant** [comment]
Yes, seems fixed with latest ozw. Switch_1 and Switch_2 are now named Instance_1:_Switch_1 and Instance_2:_Switch_2

**Comment by carsten19** [comment]
That's actually a feature from openzwave 1.6, you can assign labels to multi switches.
Should work with current openzwave.

**Comment by carsten19** [comment]
@jupzup please verify if it works

**Comment by carsten19** [comment]
Can be closed, definitely works with ozwave 1.6
