### ISSUE TITLE
Installation process is buggy, slow and ineffective

### ISSUE THREAD

**Issue by ekarak** [ioBroker/ioBroker.zwave#6]
- installOpenZWave() is called twice: once for installing the iobroker module, and then again for adding a new instance
- upon the 2nd invocation the 'unzip master.zip' is silently stalling the process (probably because it prompts for file overwriting?) and needs killing
- we shouldn't need to **compile** OpenZWave if its already installed!
- precompiled packages should be used when possible. It takes **hours** to compile OpenZWave on a Raspberry1 !

**Comment by ekarak** [comment]
I'll fork and try to provide a patch within the weekend

**Comment by Apollon77** [comment]
thank you!
When you create yourself an account on travis-ci.org and/or ci.appveyor.com you can commit in your fork and let it install on several linux, macos and windows environments with several node versions ... this is also enabled for the main repository here.
With this you can verify that the installation process works out after changes (at least very basic) :-)

**Comment by ekarak** [comment]
Great news, OpenZWave has been promoted to the 'testing' Debian repo: 
https://tracker.debian.org/pkg/openzwave

Question: do you think it's sane to use 'sudo' from within the installation scripts?

**Comment by Apollon77** [comment]
"testing" for which debian version(s)?

**Comment by buanet** [comment]
> Question: do you think it's sane to use 'sudo' from within the installation scripts?

Any news to this? I have problems with these 'sudo'-calls when trying to install the adapter in a debian based docker container with hosts-network enabled. 
Sudo isn't working in this case, so the installation returns an error...
(Note: you are always root inside a docker container, so sudo is not necessary in this case)

**Comment by Apollon77** [comment]
The questions are about alternatives. The installation process compiles and installs the zwave library and for this "root rights" are needed :-( (from my knowlede)

if you find a way to reach the same goal without sudo stuff you are more then welcome to do a Pull-Request :-)

**Comment by carsten19** [comment]
@Apollon77 @AlCalzone what do you want to do with that issue?

**Comment by AlCalzone** [comment]
I think it has been improved since - not perfect though. We could look into installing precompiled libs, but don't have the time to do that.

**Comment by carsten19** [comment]
ozwave is still not available for stretch I think so that's not really worth the effort.
I do have a small patch to suppress the warnings from the script.

**Comment by carsten19** [comment]
> * installOpenZWave() is called twice: once for installing the iobroker module, and then again for adding a new instance

Done

> * upon the 2nd invocation the 'unzip master.zip' is silently stalling the process (probably because it prompts for file overwriting?) and needs killing

Done

> * we shouldn't need to **compile** OpenZWave if its already installed!

Done

> * precompiled packages should be used when possible. It takes **hours** to compile OpenZWave on a Raspberry1 !

That's the tricky part. The openzwave library from Debian is version 1.5. There are some  precompiled versions available on the openzwave download server but for example for not arm.
If there is a proper way to access precompiled versions for most OS I can include it but right now I don't see the value.

**Comment by carsten19** [comment]
@Apollon77 from my perspective: won't fix and can be closed as long as openzwave 1.6 is not available in a common repo

**Comment by Apollon77** [comment]
then we close here for now
