### ISSUE TITLE
Rauchmelder von Devolo 

### ISSUE THREAD

**Issue by Rumpelstilzche** [ioBroker/ioBroker.zwave#61]
Hallo
Ich habe einen Rauchmelder von Devolo gekauft, und ich habe ein Problem mit der Verbindung. Ich habe 2 Mal gekauft, aber den Rauchmelder kann ich nicht mit iobroker verbinden
kann jemand mir helfen bitte 
mit freundlichen grüßen
Tolas

**Comment by carsten19** [comment]
Ich würde da eher im iobroker Forum nachfragen. Das hier ist für issues und mit diesen dürftigen Informationen wird keiner in der Lage sein zu helfen.

**Comment by carsten19** [comment]
@tolas9 welches Produkt, welche Version von z-wave, was ist das genaue Fehlerbild, was hast du versucht, ....?

**Comment by carsten19** [comment]
@Apollon77 kann geschlossen werden, keine Rückmeldung
