### ISSUE TITLE
Manufacturer/Product missing on the MCO Home CO2 sensor

### ISSUE THREAD

**Issue by OleksiyAntonov** [ioBroker/ioBroker.zwave#65]
1. Environment:
 1.1. ioBroker in Docker (buanet) on Synology
 1.2. node: v8.15.0
 1.3.  npm: v6.4.1
 1.4. ioBroker.zwave: v1.5.1
2. Sensor: MCO Home CO2 (MCOEMH9-CO2) Multilevel Sensor [(link to docu)](http://manual.zwave.eu/backend/make.php?lang=en&sku=MCOEMH9-CO2-230)
3. Pre-conditions:
  3.1. Update 1.4.2 -> 1.5.1
  3.2. Container stopped
  3.3. Host system restarted
  3.4. Container started
4. Steps to reproduce:
  4.1. Open instance settings dialog ->Devices
  4.2. Check "Manufacturer" string for the MCO sensor
  4.3. Check "Product" string for the MCO sensor
  4.4. Call "Refresh Info" command
  4.5. Wait (check status by log)
  4.6. Check "Manufacturer" string for the MCO sensor
  4.7. Check "Product" string for the MCO sensor
5. Actual results
  5.1. "Manufacturer" column contains "Unknown: id=015f"
  5.2. "Product" column contains "Unknown: type=0902, id=5102"
5. Expected results:
  5.1. On 4.2 and 4.6 it should by real manufacturer description (like in version 1.4.2) - "MCO Home ..."
  5.2. On 4.3 and 4.7 it should by real product description (also missed in version 1.4.2)

**Comment by AlCalzone** [comment]
The manufacturer descriptions are provided by OpenZWave. I don't think we can do anything here. Your combination of product type and ID seems to be missing from this list:
https://github.com/OpenZWave/open-zwave/blob/master/config/manufacturer_specific.xml#L1114

I think your best bet is to open an issue over there.

**Comment by carsten19** [comment]
@OleksiyAntonov https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by OleksiyAntonov** [comment]
@cburghardt thank you, we can close an issue
