### ISSUE TITLE
Karte vom Netzwerk nicht leserlich

### ISSUE THREAD

**Issue by Stormbringer11** [ioBroker/ioBroker.zwave#76]
Hallo,

erst mal wieder Danke für das neue coole Feature. Aber bei mir kann ich auf der Karte leider nichts erkennen. Schaut aus wie ein riesen Wollkneul der sich ständig hin und her bewegt wie ein Schwarm Bienen oder Fliegen. 

Getestet unter macOS mit Chrome und Safari. Jeweils aktuelle Versionen.

**Comment by LaplaceII** [comment]
Hallo,

bei mir das Gleiche. Auch getestet mit versch. Browsern...anbei noch ein kurzer Clip...
[video2.zip](https://github.com/ioBroker/ioBroker.zwave/files/3588041/video2.zip)


.

**Comment by carsten19** [comment]
Bei vielen Verbindungen (die gut sind) kann es etwas unübersichtlich werden.
Aber die Karte kann beliebig gezoomt werden (auch beispielsweise per Maus-Scrolling) und außerdem sind natürlich die einzelnen Knoten auswählbar.

**Comment by Stormbringer11** [comment]
Nein leider nicht die schwirren so rum, da kann man nichts erkennen. Die Karte ist nicht statisch die bewegt sich ständig.

**Comment by carsten19** [comment]
OK das ist allerdings seltsam, ich habe es unter Mac mit Safari und Chrome getestet und die Karte ist statisch. Das könnte nur an der Auflösung liegen. Ist jemand bereit das gemeinsam zu testen?

**Comment by Stormbringer11** [comment]
Wenn ich es kann gern. Mein iMac ist ein 27" mit 5120 x 2880

**Comment by carsten19** [comment]
Ins Verzeichnis /opt/iobroker wechseln. Die Datei node_modules/iobroker.zwave/admin/index.html mit einem Editor öffnen.
Den folgenden Abschnitt finden (Zeile 360):
```
         var options = {
             edges: {
                 arrows: 'to'
            }
         };
```
ersetzen durch:
```
         var options = {
            clickToUse: true,
            autoResize: false,
             edges: {
                 arrows: 'to'
            },
            physics: { 
                solver: 'repulsion' 
             }
         };
```

Abspeichern und folgendes eingeben:
./iobroker upload zwave

Dann die Netzwerkkarte erneut prüfen.

**Comment by Stormbringer11** [comment]
Das ging zwar jetzt hart an meine Linuxkenntnisgrenzen aber glaube habs richtig gemacht ;D Nur leider fliegt die Karte noch immer umher. Muß ich das jetzt wieder rückgängig machen? Hab nur ein Produktiv- und kein Testsystem :-)

**Comment by carsten19** [comment]
Nein, die Änderungen tun nicht weh. Das Video von Laplacell kann ich leider nicht öffnen, somit habe ich keine Ahnung wie das umherfliegen aussieht.
Sind denn alle Knoten am wandern oder nur das Zentrum, also der Controller?

**Comment by Stormbringer11** [comment]
Achso ;o) kannst das öffnen?
[IMG_1552.MOV.zip](https://github.com/ioBroker/ioBroker.zwave/files/3595436/IMG_1552.MOV.zip)

Alles schwirrt umher...

**Comment by carsten19** [comment]
Alles klar, danke das hilft. Sieht zwar cool aus, war aber nicht so gedacht. Ich denke ich habe eine Idee was das sein könnte, da probiere ich heute Abend was aus.

**Comment by Stormbringer11** [comment]
Ok, freut mich ;o) 
PS: Nur so zum Aufbauen *g* Ansonsten läuft der Adapter jetzt echt top, findet alle Geräte nach dem Anlaufen. Das war noch nie der Fall. Früher war ein Neustart echter Horror bis alles wieder einigermaßen ging. Jetzt flutscht er fast so wie alle anderen Adapter. Also Top Arbeit *g* Das einzige was ich noch immer habe ist, dass Bewegungssensoren "kleben" bleiben. Also den State nicht ändern. Hast du da auch eine Ahnung woher das kommen könnte?

**Comment by carsten19** [comment]
Gut, dann probieren wir doch mal was aus. 
```
        var options = {
            edges: {
                arrows: 'to'
            },
            physics: { 
                enabled: false
            }
        };
        var network = new vis.Network(container, data, options);  
        network.stabilize(100);
```
Das ersetzt den vorherigen Teil und die nächste Zeile des originalen Code.
Ich denke das sollte es fixen.

Wegen Bewegungssensoren am Besten ein separates issue aufmachen mit genauer Beschreibung und dem Typ des Gerätes

**Comment by Stormbringer11** [comment]
Bist ein Hund ;-) Das wars.... Die Karte bewegt sich jetzt nicht mehr aber erkennen tut man trotzdem nicht viel. Soweit auseinander schieben geht gar nicht aber mehr wird das Teil nicht hergeben oder? 

<img width="2339" alt="Bildschirmfoto 2019-09-11 um 01 06 09" src="https://user-images.githubusercontent.com/43651672/64656737-aa2b6480-d430-11e9-8d19-de769aee80b9.png">


Ok danke, wenn ich dich nicht nerve dann bekommst noch 2 neue Issues demnächst ;o)

**Comment by carsten19** [comment]
Wow, da gibt es ein paar zentrale Komponenten mit sehr vielen Verbindungen. Ich denke nicht dass man da noch viel machen kann, aber ich werde mal schauen ob man was mit Farben verbessern kann. Aber das ist ein separates Thema, erst mal publiziere ich den Fix.

**Comment by Stormbringer11** [comment]
Farben ist eine gute Idee. Weiß nicht ob und mit wie viel Aufwand es machbar wäre.... Ein Schieberegler um alle Knoten gleichmäßig auseinander zu ziehen würde sie glaub ich lesbar machen.
Den Issue kann ich dann schließen oder?

**Comment by carsten19** [comment]
Ja kann geschlossen werden. Ist in der Version 1.6.1 drin, ich warte nur auf den merge.
