### ISSUE TITLE
Raspberry 3 + Z-Wave Me RaZberry Modul, ZME_RAZ_EU

### ISSUE THREAD

**Issue by steveknoefler** [ioBroker/ioBroker.zwave#8]
Hello,
it is not possible to use this module in your openzwave connector.  have you any ideas for me?

https://www.amazon.de/Z-Wave-Me-RaZberry-Modul-ZME_RAZ_EU/dp/B00BL9QFH6/ref=sr_1_1?ie=UTF8&qid=1484289249&sr=8-1&keywords=raspberry+zwave

**Comment by Apollon77** [comment]
What exactly is the problem? Do you see errormessages? Can you use the module without ioBroker directly?

**Comment by Apollon77** [comment]
Do you have checked e.g. http://razberry.z-wave.me/index.php?id=29 ?!

**Comment by steveknoefler** [comment]
i will check that link later at home but the modul worked fine with zwave.me software
Error failed to start driver. if i change permissions with chmod 777 /dev/ttyAMA0 i recive another error

**Comment by Apollon77** [comment]
The Adapter uses openzwave to provide the functionality, so maybe check for infos there (Google razberry openzwave) ..

**Comment by steveknoefler** [comment]
i solved the problem as following
i installed the zwave.me software which setup rasperry for this modul
then i stopped wave.me sudo /etc/init.d/z-way-server stop

then export LD_LIBRARY_PATH=/usr/local/lib
sudo ldconfig

and i works :)

thanks for help

**Comment by Apollon77** [comment]
Cool could you write this as info also in the ioBroker.Forum, so that other users can find that info too?! Thank you!
