### ISSUE TITLE
Verify Compact mode for your adapter

### ISSUE THREAD

**Issue by ioBrokerChecker** [ioBroker/ioBroker.zwave#89]
We have detected that your adapter supports the compact mode. Please use the latest js-controller 2.0 and verify that everything works.

Some more information what is important to check can be found at https://github.com/ioBroker/ioBroker.js-controller/issues/512 

On questions please answer to the linked issue. Please close this issue after your test and add the version number that you have tested please as a comment.

Thank you for your support.

**Comment by AlCalzone** [comment]
@cburghardt something for you?

**Comment by carsten19** [comment]
@AlCalzone I have tested wave 1.7.0 with js-controller 2.0.34 and .35 and did not encounter any issues on my test system with compact mode.
