### ISSUE TITLE
Secure Connection to Danalock 

### ISSUE THREAD

**Issue by ufahrbach** [ioBroker/ioBroker.zwave#9]
Hi,
I tried to establish a secure Z-Wave connection to a Danalock. I've uncommented the according Opton NetworkKey in the options file before. When I try to connect the Dana first I see as type a Secure Door Lock Keypad, but after a few seconds that changes to Door Lock Keypad	and I get only basic access to the lock.
Openzwave for sure supports secure connections and my java script knowledge is very, very basic, but other systems using openzwave do establish such a secure connection with another function (establish secure connection or so) and use a different extended command in openzwave. I haven't seen such in the current version of the iobroker adapter.
So do you support secure connections yet?
Thanks in advance
     Uwe

**Comment by Pmant** [comment]
You may try this branch: https://github.com/Pmant/ioBroker.zwave
It adds another button to add secure devices but I'm not sure if it works.

**Comment by Venni27** [comment]
Same here. Not possible to connect a secured connection to DanaLock V3.
The other branch as mentioned obove, seems to be older and is not really maintained anymore.
Would be nice to get this to work.
The error when I try to establish a secure connection: 
`2018-08-18 13:10:55.401 - info: zwave.0 controller command feedback: state: "Command invocation had error(s) and was aborted", error: "Failed", helpmsg: "ControllerCommand - Error - Failed"`

**Comment by carsten19** [comment]
@ufahrbach secure connections are supported by the adapter. Please verify or close.

**Comment by carsten19** [comment]
@Apollon77 can be closed
