### ISSUE TITLE
Netzwerkkarte funktioniert nicht

### ISSUE THREAD

**Issue by Stormbringer11** [ioBroker/ioBroker.zwave#94]
Beim Aufruf der Netzwerkkarte kommt folgende Fehlermeldung im LOG:

zwave.0	2019-11-11 19:20:11.707	error	at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
zwave.0	2019-11-11 19:20:11.707	error	at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
zwave.0	2019-11-11 19:20:11.707	error	at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
zwave.0	2019-11-11 19:20:11.707	error	at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
zwave.0	2019-11-11 19:20:11.707	error	at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
zwave.0	2019-11-11 19:20:11.707	error	at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
zwave.0	2019-11-11 19:20:11.707	error	at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
zwave.0	2019-11-11 19:20:11.707	error	at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
zwave.0	2019-11-11 19:20:11.707	error	at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3679:41)
zwave.0	2019-11-11 19:20:11.707	error	at Object.message (/opt/iobroker/node_modules/iobroker.zwave/main.js:214:65)
zwave.0	2019-11-11 19:20:11.707	error	TypeError: Cannot read property 'common' of undefined
zwave.0	2019-11-11 19:20:11.705	error	message messagebox.system.adapter.zwave.0 [object Object] Cannot read property 'common' of undefined

**Comment by carsten19** [comment]
In GitHub Version gefixt (commit #91 )

**Comment by Stormbringer11** [comment]
Super, danke. Geht 👍🏻
